### ISSUE TITLE
implement some kind of instruction/call limit

### ISSUE THREAD

**Issue by walksanatora** [dylibso/chicory#233]
I am looking for something that would allow me to eg: call a WASM main function. have it execute 100k instructions and then return to java where I can then later call eg: `.resume()` where it would run another 100k instructions (or until it exits/returns)

**Comment by bhelx** [comment]
We don't support that today, but it's certainly an interesting idea! I bet it's something you could easily implement in a fork of chicory if you wanted to give it a shot. You could keep a counter of instructions consumed, then call a host function when you reach a limit. when the host function returns then it could resume naturally.

I do think it would require more discussion for us to support it though.

**Comment by andreaTP** [comment]
Thanks for your interest in the project!

It's an interesting idea, probably, a little early to support it.
I would be interested in looking at a strawman but I cannot promise it can easily land soon.
Unfortunately, we still need to finish a lot of work to fully support the spec and this proposal goes beyond it, still, if there is a way to support it almost seamlessly and with very little code I'm open to evaluate it!

**Comment by andreaTP** [comment]
For reference `wasmtime` has an option for something similar:

```
      --fuel <N>
          Enable execution fuel with N units fuel, where execution will trap after running out of fuel.
          
          Most WebAssembly instructions consume 1 unit of fuel. Some instructions, such as `nop`, `drop`, `block`, and `loop`, consume 0 units, as any execution cost associated with them involves other instructions which do consume fuel.
```

**Comment by evacchi** [comment]
I think what wasmtime does in this case is injecting counters at strategic places by rewriting the wasm module (at least that's what the fuzzer seems to do 😬)

**Comment by danielperano** [comment]
There are a few decent ways to go about this, with different drawbacks depending on whether you're running interpreted or AOT. In interpreted mode, I'd probably support an optional "pre-execution" handler that runs (if provided) before each opcode or before each `nth` opcode where `n` is configurable (the latter scheme should have a bit less overhead).

In AOT mode, this is a prohibitive overhead, and to make matters worse one can't just suspend/resume a callstack at will, at least not explicitly. My approach in Chipmunk (no useful WIP to link yet, unfortunately) is to configure a set of "safepoints" where the AOT compiler will inject trap calls to a supplied trap handler - so the AOT can be configured to trap immediately before allocations, backjumps (typically a return to the top of a loop), method calls, etc. That lets you cut down the overhead to one that will only occur in specific scenarios. Trap handlers can do anything - throw an uncatchable exception to abort execution, suspend a virtual thread, etc.

I like the `trap` concept because it's (loosely) analogous to how hardware/OSs handle some of these concerns (so it quite naturally fits bytecode generation or execution models), and it's very flexible in what you do when a trap is called so you can use it for lots of things like this (albeit with lower resolution than being able to stop at any arbitrary `nth` opcode, though personally I consider that to be a high-overhead constraint that's usually not needed at such high precision). Traps would rather easily allow us to share a close (if not identical) API between interpreter and AOT modes, and users might even be able to re-use trap handler implementations.

**Comment by bhelx** [comment]
I'd love to get a plan for this worked out as it will be pretty important for production use. I think counting each instruction, while it would work and be simple, would be extremely slow.

> I think what wasmtime does in this case is injecting counters at strategic places by rewriting the wasm module (at least that's what the fuzzer seems to do 😬)

This is a pretty good option. I was thinking this could be part of some extended intermediate representation of Wasm. Like we have some opcodes that will never be in the spec that are responsible for incrementing the instruction counter by `n`. But we could probably also do this with normal globals and not have to worry about our engines handling made up instructions. And perhaps there exist some tooling or algorithms we can re-use to inject the counters. The one thing that would be most challenging is figuring out where to inject the checks without degrading performance.

@evacchi do you know if their injection stuff seems re-usable or not? Whoever tackles this should definitely study the wasmtime implementation first. It would be great if we could just re-use some outside tooling for this and not have to invent it ourselves.

> There are a few decent ways to go about this, with different drawbacks depending on whether you're running interpreted or AOT. In interpreted mode, one way to do this (that I could see working nicely) is to run an optional handler before each nth opcode where n is configurable.

That's a pretty nice and simple way to do it. Sort-of like counting every instruction but not having to have millions of if statements, and you could give the end user some control over how aggressive they want to be.

> In AOT mode, this is a prohibitive overhead, and to make matters worse one can't just suspend/resume a callstack at will, at least not explicitly. My approach in Chipmunk (no useful WIP to link yet, unfortunately) is to configure a set of "safepoints" where the AOT compiler will inject trap calls to a supplied trap handler - so the AOT can be configured to trap immediately before allocations, backjumps (typically a return to the top of a loop), method calls, etc. That lets you cut down the overhead to one that will only occur in specific scenarios. Trap handlers can do anything - throw an uncatchable exception to abort execution, suspend a virtual thread, etc.

Yeah that's the tricky piece. Where do we inject the checks? The challenge is you don't want to check so often that it degrades performance, but you also need to consider that someone who wishes to exhaust CPU on your system knows the algorithm and can craft a binary that might get around the checks. What you're suggesting sounds right but maybe I'm not thinking adversarially enough.

**Comment by danielperano** [comment]
You can fully stop potential CPU exhaustion if you insert a check before every back jump (jump to an earlier instruction in the sequence - very much analogous to inserting a check at the end of a loop body but more generalized) and before every function call (to prevent long-running recursion or other functional tricks).

In most code I expect the per-call checks to be the most expensive, but I think there are some easy heuristics that could cut down on overhead, such as only inserting checks before non-terminal functions (functions that do not call other functions). Terminality in this sense is trivially determined by inspecting the opcodes of the function. Fine tuning can be done by making this configurable - whitelisting certain functions, adjusting check insertion rules, etc.

**Comment by evacchi** [comment]
> @evacchi do you know if their injection stuff seems re-usable or not? Whoever tackles this should definitely study the wasmtime implementation first. It would be great if we could just re-use some outside tooling for this and not have to invent it ourselves.

heh, good question. I haven't looked into it so I am not sure 🤔 I've been thinking about some generic bytecode-rewriting/injection solution

**Comment by electrum** [comment]
> You can fully stop potential CPU exhaustion if you insert a check before every back jump (jump to an earlier instruction in the sequence - very much analogous to inserting a check at the end of a loop body but more generalized) and before every function call (to prevent long-running recursion or other functional tricks).

That's what we did in https://github.com/dylibso/chicory/commit/b32a23b1ef44feb48a02a3b6e25ee5e440e4b7d9 to check for thread interruption.

**Comment by andreaTP** [comment]
Implemented a viable way to tackle the original issue in #308 , please feel free to open a new issue if it requires more refinement.
